import React from "react";

const SEOKeywordCloud = () => {
  const keywords = [
    "Best resume maker for freshers in India 2026",
    "Free resume maker for IT freshers India",
    "ATS-friendly resume templates for India freshers 2026",
    "Free online CV maker India for engineering freshers 2026",
    "AI-powered resume builder for Indian fresh graduates 2026",
    "Professional resume format for freshers in India 2026",
    "Resume maker for students in India free",
    "Online resume builder for campus placements India",
    "Best CV format for IT freshers in India",
    "Resume builder for 1st year engineering students India",
    "Python developer resume for freshers India",
    "Java developer resume format for freshers 2026",
    "React JS developer resume for freshers India",
    "Data science resume sample for freshers India",
    "Software engineer resume for freshers India 2026",
    "Web developer resume for freshers India",
    "Full stack developer resume for freshers India",
    "DevOps engineer resume for freshers 2026",
    "Cybersecurity resume for freshers India",
    "AI ML engineer resume for freshers India",
    "Cloud computing resume for freshers 2026",
    "Mobile app developer resume for freshers India",
    "QA tester resume for freshers India",
    "UI UX designer resume for freshers India",
    "Business analyst resume for freshers 2026",
    "Why ATS rejects resumes in India and how to fix it",
    "ATS score checker for Indian resumes free",
    "Resume keyword optimization for IT jobs India",
    "How to pass ATS for MNC jobs in India",
    "ATS-friendly resume format for TCS",
    "ATS-friendly resume format for Infosys",
    "ATS-friendly resume format for Wipro",
    "ATS-friendly resume format for HCL",
    "ATS-friendly resume format for Cognizant",
    "ATS-friendly resume format for Accenture",
    "Best keywords for IT fresher resume India",
    "Action verbs for engineering resume India",
    "Resume formatting tips for ATS India",
    "Standard resume font for ATS India",
    "CV vs Resume difference for India jobs",
    "Resume for campus placement engineering India",
    "Entry-level IT jobs in Bangalore for freshers 2026",
    "IT jobs for freshers in Hyderabad 2026",
    "Software jobs in Pune for freshers 2026",
    "Fresher jobs in Chennai for engineering students",
    "Off-campus placement resume tips India",
    "How to get a job in top MNC India as a fresher",
    "Resume for 0 years experience IT India",
    "Professional summary for freshers in India",
    "Objective for resume for freshers engineering",
    "Free PDF resume download for freshers India",
    "Modern resume templates for freshers India",
    "Creative resume for freshers India 2026",
    "Minimalist resume format for India",
    "Single column resume for freshers India",
    "Two column resume for freshers India",
    "Resume with photo format for India 2026",
    "Skills based resume for freshers India",
    "Chronological resume for freshers India",
    "Hybrid resume format for India",
    "Resume for mechanical engineering freshers India",
    "Resume for civil engineering freshers India",
    "Resume for electrical engineering freshers India",
    "Resume for BBA freshers in India",
    "Resume for MBA freshers India 2026",
    "Resume for BCA freshers India",
    "Resume for MCA freshers India 2026",
    "Resume for B.Com freshers India",
    "Resume for non-IT graduates looking for IT jobs",
    "Career gap resume for freshers India",
    "AI resume analyzer for Indian freshers",
    "ChatGPT resume builder for freshers India",
    "Automated resume writing for Indian students",
    "AI suggestions for fresher resumes India",
    "Best AI tool for resume building in India 2026",
    "Resume for internship for college students India",
    "Portfolio website vs Resume for Indian freshers",
    "LinkedIn profile optimization for freshers India",
    "Cover letter for freshers in India format",
    "Thank you email after interview India",
    "Hobby section in resume for freshers India",
    "Languages known in resume for India",
    "Declaration in resume for freshers India",
    "Reference section in resume India",
    "Resume for remote IT jobs India freshers",
    "Salary expectation for IT freshers India 2026",
    "Best cities for IT freshers in India",
    "Top MNC companies for freshers in India",
    "How to write projects in resume for freshers",
    "Certifications for IT freshers resume India",
    "IT hiring trends India 2026",
    "Skills to learn for IT jobs 2026 India",
    "Resume format change in 2026 India",
    "Digital first resume for India 2026",
    "Video resume tips for Indian freshers 2026",
    "Resume maker online India with one-time payment",
    "Affordable resume services for freshers India",
    "Resume for startup jobs India freshers",
    "Resume for product based companies India",
    "Resume for service based companies India",
    "How to build a strong resume as a fresher in India",
    "Essential resume components for freshers India",
    "Professional branding for Indian students",
    "Career guidance for engineering freshers India 2026",
    "Job winning resume strategies for India",
  ];

  return (
    <footer className="sr-only" aria-hidden="true">
      <h2>Search Keywords for NextCV Resume Builder</h2>
      <ul>
        {keywords.map((keyword, index) => (
          <li key={index}>{keyword}</li>
        ))}
      </ul>
    </footer>
  );
};

export default SEOKeywordCloud;
