const resumeTemplateCatalog = [
  {
    tierName: "Basic",
    description: "Essential template for freshers and mass recruitment.",
    badge: "Beginner Friendly",
    highlight: false,
    templates: [
      {
        templateName: "modernTemplate",
        style: "Clean Modern Style",
        priceOriginal: 99,
        priceDiscounted: 49,
        savings: 50,
        discountPercent: 50,
        tag: "Popular",
      },
    ],
  },

  {
    tierName: "Standard",
    description: "Professional ATS templates for freshers and job seekers.",
    badge: "Best Starter Pack",
    highlight: false,
    templates: [
      {
        templateName: "TcsDigital",
        style: "🔥 ATS Optimized",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
        tag: "Best Value",
      },
      {
        templateName: "InfosysSystem",
        style: "🔥 ATS Optimized",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "CompactModern",
        style: "🔥 ATS Optimized",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
        tag: "Recommended",
      },
      {
        templateName: "classicTemplate",
        style: "Classic Layout",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
    ],
  },

  {
    tierName: "Premium",
    description:
      "Best-value pack with advanced templates for corporate, tech, and specialized roles.",
    badge: "🔥 Most Popular",
    highlight: true,
    templates: [
      {
        templateName: "MordenBluesidebar",
        style: "Sidebar Layout",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "WiproModern",
        style: "Classic Layout",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "AmazonOperations",
        style: "Corporate",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "AccentureConsult",
        style: "Corporate",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "HclTech",
        style: "Corporate",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "IbmClassic",
        style: "Corporate",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "DeloitteAudit",
        style: "Corporate",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "OracleDb",
        style: "Corporate",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "MahindraRise",
        style: "Corporate",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "MedicalNurse",
        style: "Specialized",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "ClinicalTrial",
        style: "Specialized",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "AcademicTeacher",
        style: "Education",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "LegalProfessional",
        style: "Law",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "SalesGrowth",
        style: "Sales / Marketing",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "MarketingCreative",
        style: "Sales / Marketing",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "SapEnterprise",
        style: "ERP / Tech",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "MinimalistTemplate",
        style: "Clean Style",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "ProfessionalClean",
        style: "Clean Style",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
        tag: "🔥 Recruiter पसंद",
      },
      {
        templateName: "AppleCreative",
        style: "Sleek Modern",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "SidebarLeft",
        style: "Sidebar Layout",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "CapgeminiFlow",
        style: "Branded Design",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "CiscoNet",
        style: "Branded Design",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "ExecutiveGray",
        style: "Corporate / Sleek",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
      {
        templateName: "BoldHeader",
        style: "Attention-grabbing",
        priceOriginal: 399,
        priceDiscounted: 199,
        savings: 200,
        discountPercent: 50,
      },
    ],
  },

  {
    tierName: "Elite",
    description: "Complete access to top tech, finance, creative, and standout resume templates.",
    badge: "👑 All Templates + Future Updates",
    highlight: false,
    templates: [
      {
        templateName: "GoogleTech",
        style: "Top Tech Firms",
        priceOriginal: 799,
        priceDiscounted: 399,
        savings: 400,
        discountPercent: 50,
        tag: "High Success Rate",
      },
      {
        templateName: "NavyEdge",
        style: "Top Tech Firms",
        priceOriginal: 799,
        priceDiscounted: 399,
        savings: 400,
        discountPercent: 50,
        tag: "High Success Rate",
      },
      {
        templateName: "MicrosoftCorp",
        style: "Top Tech Firms",
        priceOriginal: 799,
        priceDiscounted: 399,
        savings: 400,
        discountPercent: 50,
      },
      {
        templateName: "MetaSocial",
        style: "Top Tech Firms",
        priceOriginal: 799,
        priceDiscounted: 399,
        savings: 400,
        discountPercent: 50,
      },
      {
        templateName: "JpmorganChase",
        style: "Finance",
        priceOriginal: 799,
        priceDiscounted: 399,
        savings: 400,
        discountPercent: 50,
      },
      {
        templateName: "GoldmanFinance",
        style: "Finance",
        priceOriginal: 799,
        priceDiscounted: 399,
        savings: 400,
        discountPercent: 50,
      },
      {
        templateName: "TechDark",
        style: "Dark Mode / Trendy",
        priceOriginal: 799,
        priceDiscounted: 399,
        savings: 400,
        discountPercent: 50,
        tag: "🔥 Premium Pick",
      },
      {
        templateName: "InfographicLite",
        style: "Visual Data",
        priceOriginal: 799,
        priceDiscounted: 399,
        savings: 400,
        discountPercent: 50,
      },
      {
        templateName: "NetflixCulture",
        style: "Branded / Standout",
        priceOriginal: 799,
        priceDiscounted: 399,
        savings: 400,
        discountPercent: 50,
      },
      {
        templateName: "CreativeTeal",
        style: "Bold Creative",
        priceOriginal: 799,
        priceDiscounted: 399,
        savings: 400,
        discountPercent: 50,
      },
    ],
  },
];

export default resumeTemplateCatalog;
