const resumeTemplateCatalog = [
  // 🟢 Basic Tier
  {
    tierName: "Basic",
    description: "Essential templates for freshers and mass recruitment.",
    badge: "Beginner Friendly",
    highlight: false,
    templates: [
      {
        templateName: "modernTemplate",
        style: "Clean Modern Style",
        priceOriginal: 99,
        priceDiscounted: 49,
        savings: 50,
        discountPercent: 50,
        tag: "Popular",
      },
      {
        templateName: "MordenBluesidebar",
        style: "Sidebar Layout",
        priceOriginal: 99,
        priceDiscounted: 49,
        savings: 50,
        discountPercent: 50,
      },
      {
        templateName: "classicTemplate",
        style: "Classic Layout",
        priceOriginal: 99,
        priceDiscounted: 49,
        savings: 50,
        discountPercent: 50,
      },
    ],
  },

  // 🔵 Standard Tier
  {
    tierName: "Standard",
    description: "Professional templates for experienced and niche roles.",
    badge: "🔥 Most Popular",
    highlight: true,
    templates: [
      {
        templateName: "TcsDigital",
        style: "🔥 ATS Optimized",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
        tag: "Best Value",
      },
      {
        templateName: "InfosysSystem",
        style: "🔥 ATS Optimized",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "CompactModern",
        style: "🔥 ATS Optimized",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
        tag: "Recommended",
      },

      {
        templateName: "WiproModern",
        style: "Classic Layout",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "AmazonOperations",
        style: "Corporate",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "AccentureConsult",
        style: "Corporate",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "HclTech",
        style: "Corporate",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "IbmClassic",
        style: "Corporate",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "DeloitteAudit",
        style: "Corporate",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "OracleDb",
        style: "Corporate",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "MahindraRise",
        style: "Corporate",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },

      {
        templateName: "MedicalNurse",
        style: "Specialized",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "ClinicalTrial",
        style: "Specialized",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "AcademicTeacher",
        style: "Education",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "LegalProfessional",
        style: "Law",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },

      {
        templateName: "SalesGrowth",
        style: "Sales / Marketing",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "MarketingCreative",
        style: "Sales / Marketing",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },

      {
        templateName: "SapEnterprise",
        style: "ERP / Tech",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "MinimalistTemplate",
        style: "Clean Style",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
      {
        templateName: "ProfessionalClean",
        style: "Clean Style",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
        tag: "🔥 Recruiter पसंद",
      },

      {
        templateName: "AppleCreative",
        style: "Sleek Modern",
        priceOriginal: 199,
        priceDiscounted: 99,
        savings: 100,
        discountPercent: 50,
      },
    ],
  },

  // 🟣 Premium Tier
  {
    tierName: "Premium",
    description: "Modern & tech-focused templates for developers and product-based roles.",
    badge: "Best for Tech Jobs",
    highlight: false,
    templates: [
      {
        templateName: "SidebarLeft",
        style: "Sidebar Layout",
        priceOriginal: 599,
        priceDiscounted: 299,
        savings: 300,
        discountPercent: 50,
      },
      {
        templateName: "GoogleTech",
        style: "Top Tech Firms",
        priceOriginal: 999,
        priceDiscounted: 499,
        savings: 500,
        discountPercent: 50,
        tag: "High Success Rate",
      },
      {
        templateName: "MicrosoftCorp",
        style: "Top Tech Firms",
        priceOriginal: 999,
        priceDiscounted: 499,
        savings: 500,
        discountPercent: 50,
      },
      {
        templateName: "MetaSocial",
        style: "Top Tech Firms",
        priceOriginal: 999,
        priceDiscounted: 499,
        savings: 500,
        discountPercent: 50,
      },

      {
        templateName: "JpmorganChase",
        style: "Finance",
        priceOriginal: 999,
        priceDiscounted: 499,
        savings: 500,
        discountPercent: 50,
      },
      {
        templateName: "GoldmanFinance",
        style: "Finance",
        priceOriginal: 999,
        priceDiscounted: 499,
        savings: 500,
        discountPercent: 50,
      },

      {
        templateName: "CapgeminiFlow",
        style: "Branded Design",
        priceOriginal: 599,
        priceDiscounted: 299,
        savings: 300,
        discountPercent: 50,
      },
      {
        templateName: "CiscoNet",
        style: "Branded Design",
        priceOriginal: 599,
        priceDiscounted: 299,
        savings: 300,
        discountPercent: 50,
      },

      {
        templateName: "ExecutiveGray",
        style: "Corporate / Sleek",
        priceOriginal: 599,
        priceDiscounted: 299,
        savings: 300,
        discountPercent: 50,
      },
      {
        templateName: "BoldHeader",
        style: "Attention-grabbing",
        priceOriginal: 599,
        priceDiscounted: 299,
        savings: 300,
        discountPercent: 50,
      },
    ],
  },

  // 🔴 Elite Tier
  {
    tierName: "Elite",
    description: "High-value templates for creative portfolios and standout resumes.",
    badge: "Limited Offer",
    highlight: false,
    templates: [
      {
        templateName: "TechDark",
        style: "Dark Mode / Trendy",
        priceOriginal: 1499,
        priceDiscounted: 599,
        savings: 900,
        discountPercent: 60,
        tag: "🔥 Premium Pick",
      },
      {
        templateName: "InfographicLite",
        style: "Visual Data",
        priceOriginal: 1499,
        priceDiscounted: 599,
        savings: 900,
        discountPercent: 60,
      },
      {
        templateName: "NetflixCulture",
        style: "Branded / Standout",
        priceOriginal: 1499,
        priceDiscounted: 599,
        savings: 900,
        discountPercent: 60,
      },
      {
        templateName: "CreativeTeal",
        style: "Bold Creative",
        priceOriginal: 1499,
        priceDiscounted: 599,
        savings: 900,
        discountPercent: 60,
      },
    ],
  },
];

export default resumeTemplateCatalog;
